version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        # Freshness testing - make sure to fill in the ...
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: list of all Greenweez products / we have one row per product_id with the purchase price associated
        tests:
          - unique:
              column_name: "products_id"
      - name: ship
        identifier: raw_gz_ship
        description: ships of Greenweez / we have one row per orders_id found in each orders_id and costs associated
        tests:
          - unique:
              column_name: "orders_id"
        

